spring:
  profiles:
    active: dev

server:
  port: 12000
  servlet:
    context-path: /gqt
    session:
      timeout: 54000
  tomcat:
    basedir: ./tmp

weixin:
  appid: wxe66a4e8c467b3e00
  secret: 33daf9d927d0ca8563acc43b8626d41c